### PR TITLE
Update outdated colorizations brought in by license PR 

### PR DESCRIPTION
**Pull request by kke**
There were some `pastel.xyz` usages in the LicenseInspectCommand that were not using the Colorize refinement.

### CODE REVIEW

**Comment by kke** [comment]
Maybe we need to drop the inspect command.

Or maybe it should get the JWT from the cluster. Maybe it shouldn't call the JWT a "license key", because license assign calls the UUID's license keys.

If it accepts the UUID it needs to POST it to cloud and that will assign it. So, license inspect was pretty much doing everything license assign does, except update the secret. I changed it to only validate JWT and it doesn't even do that, it only validates the contents, not the signature.

Multi-fail.

**Comment by kke** [comment]
> Maybe we need to drop the inspect command.

#1131 now defines how `license inspect` should actually work, looking into it.

**Comment by nevalla** [comment]
@kke can we close this?

**Comment by kke** [comment]
New inspect command coming

**Pull request closed without merging**
