### PR TITLE
Convert addon { .. } blocks to do .. end

### PR DESCRIPTION
**Pull request by kke**
Purely for cosmetic reasons

### CODE REVIEW

**Comment by jakolehm** [comment]
Needs also update to docs.

**Comment by kke** [comment]
You can still use `{ ... }`

**Comment by jakolehm** [comment]
> You can still use `{ ... }`

I know but if `do .. end` is the best practice we should update the docs.

**Comment by kke** [comment]
Currently there are mixed `{}` and `do end`, even in the same schemas. Need to pick one :)

**Comment by jakolehm** [comment]
> Currently there are mixed `{}` and `do end`, even in the same schemas. Need to pick one :)

I thought this PR already picked one? Or did I misunderstood something?

**Pull request closed without merging**
