### PR TITLE
Fix CentOS/RHEL7 kubelet cgroups settings

### LINKED ISSUE #440: CentOS kubelet complains about systemd slices
We should probably set `--runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice` as kubelet args on CentOS/RHEL.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #440

### CODE REVIEW

**Comment by jakolehm** [comment]
@SpComb PTAL

**Comment by SpComb** [comment]
> @SpComb PTAL

No idea what the issue or fix is about, let me bring up a CentOS machine and take a look...

**Comment by SpComb** [comment]
NACK, see https://github.com/kontena/pharos-cluster/issues/440#issuecomment-399014418 for why this workaround is a terrible idea, and https://github.com/kontena/pharos-cluster/pull/446 for a better alternative that actually fixes the issue.

**Comment by jakolehm** [comment]
Fixed in kubelet rpm package.

**Pull request closed without merging**
