### PR TITLE
Use auth namespace to store authentication tokens

### PR DESCRIPTION
**Pull request by nevalla**
TODO
- [x] ~~dedicated namespace for authentication tokens~~
- [ ] migration for existing tokens

### CODE REVIEW

**Comment by jakolehm** [comment]
Does this need a migration (for existing tokens)?

**Comment by kke** [comment]
Ping @nevalla

**Comment by kke** [comment]
Is this still relevant?

**Comment by kke** [comment]
Ping @nevalla

**Comment by nevalla** [comment]
Yes, this is still relevant but migration is required.

**Pull request closed without merging**
