### PR TITLE
Store kontena-lens config directly to the k8s api

### PR DESCRIPTION
**Pull request by jakolehm**
No more "Waiting for Kontena Lens to get up and running ...".

### CODE REVIEW

**Comment by jakolehm** [comment]
@nevalla PTAL

**Comment by nevalla** [comment]
The implementation is now 💯 times better. Only downside is that now pharos spit out lens address and credentials but dasboard is not there yet. Is that good or should we wait, for example, that dashboard pod is running or similar?

**Comment by jakolehm** [comment]
I think we could just hint that deployment of the dashboard might take a while?

**Comment by jnummelin** [comment]
Maybe have a hint like "Starting up Lens the first time might take couple of minutes, until that you'll see 503 with the address given above."

503 normally should be transient, but the user does not have any idea how long to wait for it to pass.

**Comment by jakolehm** [comment]
Improved post-install messages.

**Comment by jnummelin** [comment]
LGTM

**Comment by kke** [comment]
```
/__enclose_io_memfs__/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bcrypt_ext (LoadError)
```

**Pull request merged**
