### PR TITLE
Enable kubelet server tls bootstrap

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by jakolehm** [comment]
@jnummelin PTAL

**Comment by jakolehm** [comment]
> On a patch upgrade or regular "re-up" with same kube version, the kubelet config is not re-written. 

This is only problem if user upgrades from pre-release, right?

**Comment by jnummelin** [comment]
> This is only problem if user upgrades from pre-release, right?

AFAIK yes. But I do not see why we could not update to config on each run. We might need to fix some kubelet options on patch releases too.

**Comment by jakolehm** [comment]
> AFAIK yes. But I do not see why we could not update to config on each run. We might need to fix some kubelet options on patch releases too.

Yes but even if we store the updated config it's not applied automatically to kubelets (kubelet restart is needed).

**Pull request merged**
