### PR TITLE
Remove -00 version suffix madness from debs

### PR DESCRIPTION
**Pull request by jakolehm**
Also removes one deprecated file that I spotted file searching -00 occurrences.

### CODE REVIEW

**Comment by kke** [comment]
This does make installing  `x.y.1` impossible if there's `x.y.10` available. Is that a problem?

**Comment by jakolehm** [comment]
> This does make installing `x.y.1` impossible if there's `x.y.10` available. Is that a problem?

Ideas how to fix? Maybe `-*`?

**Comment by kke** [comment]
`-*` or `-??` seem to work but I don't know if that fixes the problem this pr is addressing.

**Comment by jnummelin** [comment]
AFAIK `-*` would allow to select the latest rev of the package

**Pull request closed without merging**
