### PR TITLE
Add host ssh_port option

### LINKED ISSUE #1062: Allow to configure port for SSH access
**What would you like to be added**:
Allow to configure SSH port for hosts

**Why is this needed**:
It's possible that nodes are behind the same public ip, but they are listening to different ssh port

**Example cluster.yml**:
```yaml
hosts:
  - address: 10.2.2.1
     port: 2022
  - address: 10.2.2.1
     port: 2023
  ...
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #1062 

Adds `ssh_port` option for hosts and bastion hosts:

```yaml
hosts:
  - address: 10.0.0.1
     ssh_port: 1234
     bastion:
       address: 10.0.0.2
       ssh_port: 2345
```

Also adds `bastion.ssh_proxy_command` for using a proxy command to start the bastion host's session.

### CODE REVIEW

**Comment by kke** [comment]
(Doc PR incoming)

**Comment by jakolehm** [comment]
Not merging before we have docs pr.

**Comment by jakolehm** [comment]
@kke waiting for the docs ...

**Comment by kke** [comment]
Noticed it's not in terraform parser, adding that still.

**Pull request merged**
