### PR TITLE
Update nginx-ingress to 0.12.0

### LINKED ISSUE #216: Upgrade ingress-nginx to 0.12.0

### PR DESCRIPTION
**Pull request by jnummelin**
fixes #216

### CODE REVIEW

**Comment by jakolehm** [comment]
No changes to yaml files?

**Comment by jnummelin** [comment]
Nope. Unless there's some new things we'd like to config. Looking at the changelog `--enable-dynamic-configuration` might make sense to configure as it's disabled by default.

@jakolehm Did you have some specific things in mind we should change in the configs?

**Comment by jakolehm** [comment]
> @jakolehm Did you have some specific things in mind we should change in the configs?

No, just wanted to double-check that configs didn't change.

**Comment by jnummelin** [comment]
I'll make separate issue for enabling the live-reload

**Pull request merged**
